package Entities;
// Generated May 13, 2017 5:10:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Answer generated by hbm2java
 */
public class Answer  implements java.io.Serializable {


     private int id;
     private Question question;
     private String answerContent;
     private Boolean isCorrect;

    public Answer() {
    }

	
    public Answer(int id) {
        this.id = id;
    }
    public Answer(int id, Question question, String answerContent, Boolean isCorrect) {
       this.id = id;
       this.question = question;
       this.answerContent = answerContent;
       this.isCorrect = isCorrect;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public String getAnswerContent() {
        return this.answerContent;
    }
    
    public void setAnswerContent(String answerContent) {
        this.answerContent = answerContent;
    }
    public Boolean getIsCorrect() {
        return this.isCorrect;
    }
    
    public void setIsCorrect(Boolean isCorrect) {
        this.isCorrect = isCorrect;
    }




}


