package Entities;
// Generated May 13, 2017 5:10:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private int id;
     private String course;
     private Date startDate;
     private Date finishDate;
     private Set subjects = new HashSet(0);
     private Set specialities = new HashSet(0);
     private Set semesters = new HashSet(0);

    public Course() {
    }

	
    public Course(int id) {
        this.id = id;
    }
    public Course(int id, String course, Date startDate, Date finishDate, Set subjects, Set specialities, Set semesters) {
       this.id = id;
       this.course = course;
       this.startDate = startDate;
       this.finishDate = finishDate;
       this.subjects = subjects;
       this.specialities = specialities;
       this.semesters = semesters;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getFinishDate() {
        return this.finishDate;
    }
    
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }
    public Set getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Set subjects) {
        this.subjects = subjects;
    }
    public Set getSpecialities() {
        return this.specialities;
    }
    
    public void setSpecialities(Set specialities) {
        this.specialities = specialities;
    }
    public Set getSemesters() {
        return this.semesters;
    }
    
    public void setSemesters(Set semesters) {
        this.semesters = semesters;
    }




}


