package Entities;
// Generated May 13, 2017 5:10:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Exam generated by hbm2java
 */
public class Exam  implements java.io.Serializable {


     private int id;
     private Examination examination;
     private Subject subject;
     private UserAccount userAccount;
     private String name;
     private int NumberOfQuestion;
     private Double duration;
     private Boolean status;
     private Date createTime;
     private Date updateTime;
     private Set examsQuestions = new HashSet(0);
     private Set studentExams = new HashSet(0);

    public Exam() {
    }

	
    public Exam(int id, Examination examination) {
        this.id = id;
        this.examination = examination;
    }
    public Exam(int id, Examination examination, Subject subject, UserAccount userAccount, String name,int NumberOfQuestion, Double duration, Boolean status, Date createTime, Date updateTime, Set examsQuestions, Set studentExams) {
       this.id = id;
       this.examination = examination;
       this.subject = subject;
       this.userAccount = userAccount;
       this.name = name;
       this.NumberOfQuestion = NumberOfQuestion;
       this.duration = duration;
       this.status = status;
       this.createTime = createTime;
       this.updateTime = updateTime;
       this.examsQuestions = examsQuestions;
       this.studentExams = studentExams;
    }

    public int getNumberOfQuestion() {
        return NumberOfQuestion;
    }

    public void setNumberOfQuestion(int NumberOfQuestion) {
        this.NumberOfQuestion = NumberOfQuestion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Examination getExamination() {
        return this.examination;
    }
    
    public void setExamination(Examination examination) {
        this.examination = examination;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public UserAccount getUserAccount() {
        return this.userAccount;
    }
    
    public void setUserAccount(UserAccount userAccount) {
        this.userAccount = userAccount;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getDuration() {
        return this.duration;
    }
    
    public void setDuration(Double duration) {
        this.duration = duration;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Set getExamsQuestions() {
        return this.examsQuestions;
    }
    
    public void setExamsQuestions(Set examsQuestions) {
        this.examsQuestions = examsQuestions;
    }
    public Set getStudentExams() {
        return this.studentExams;
    }
    
    public void setStudentExams(Set studentExams) {
        this.studentExams = studentExams;
    }




}


