package Entities;
// Generated May 13, 2017 5:10:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Examination generated by hbm2java
 */
public class Examination  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private Date createTime;
     private Date updateTime;
     private Set exams = new HashSet(0);

    public Examination() {
    }

	
    public Examination(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Examination(int id, String name, String description, Date createTime, Date updateTime, Set exams) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.createTime = createTime;
       this.updateTime = updateTime;
       this.exams = exams;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Set getExams() {
        return this.exams;
    }
    
    public void setExams(Set exams) {
        this.exams = exams;
    }




}


