package Entities;
// Generated May 13, 2017 5:10:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private int id;
     private Subject subject;
     private Byte type;
     private Integer numberOfQuestion;
     private Set answers = new HashSet(0);
     private Set examsQuestions = new HashSet(0);

    public Question() {
    }

	
    public Question(int id) {
        this.id = id;
    }
    public Question(int id, Subject subject, Byte type, Integer numberOfQuestion, Set answers, Set examsQuestions) {
       this.id = id;
       this.subject = subject;
       this.type = type;
       this.numberOfQuestion = numberOfQuestion;
       this.answers = answers;
       this.examsQuestions = examsQuestions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public Byte getType() {
        return this.type;
    }
    
    public void setType(Byte type) {
        this.type = type;
    }
    public Integer getNumberOfQuestion() {
        return this.numberOfQuestion;
    }
    
    public void setNumberOfQuestion(Integer numberOfQuestion) {
        this.numberOfQuestion = numberOfQuestion;
    }
    public Set getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Set answers) {
        this.answers = answers;
    }
    public Set getExamsQuestions() {
        return this.examsQuestions;
    }
    
    public void setExamsQuestions(Set examsQuestions) {
        this.examsQuestions = examsQuestions;
    }




}


