package Entities;
// Generated May 13, 2017 5:10:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Semester generated by hbm2java
 */
public class Semester  implements java.io.Serializable {


     private int id;
     private Course course;
     private String semester;
     private Date startDate;
     private Date finishDate;
     private Set specialities = new HashSet(0);
     private Set subjects = new HashSet(0);

    public Semester() {
    }

	
    public Semester(int id) {
        this.id = id;
    }
    public Semester(int id, Course course, String semester, Date startDate, Date finishDate, Set specialities, Set subjects) {
       this.id = id;
       this.course = course;
       this.semester = semester;
       this.startDate = startDate;
       this.finishDate = finishDate;
       this.specialities = specialities;
       this.subjects = subjects;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public String getSemester() {
        return this.semester;
    }
    
    public void setSemester(String semester) {
        this.semester = semester;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getFinishDate() {
        return this.finishDate;
    }
    
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }
    public Set getSpecialities() {
        return this.specialities;
    }
    
    public void setSpecialities(Set specialities) {
        this.specialities = specialities;
    }
    public Set getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Set subjects) {
        this.subjects = subjects;
    }




}


