package Entities;
// Generated May 13, 2017 5:10:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Specialitie generated by hbm2java
 */
public class Specialitie  implements java.io.Serializable {


     private int id;
     private Course course;
     private Semester semester;
     private String name;
     private Set userAccounts = new HashSet(0);
     private Set subjects = new HashSet(0);

    public Specialitie() {
    }

	
    public Specialitie(int id) {
        this.id = id;
    }
    public Specialitie(int id, Course course, Semester semester, String name, Set userAccounts, Set subjects) {
       this.id = id;
       this.course = course;
       this.semester = semester;
       this.name = name;
       this.userAccounts = userAccounts;
       this.subjects = subjects;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Semester getSemester() {
        return this.semester;
    }
    
    public void setSemester(Semester semester) {
        this.semester = semester;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUserAccounts() {
        return this.userAccounts;
    }
    
    public void setUserAccounts(Set userAccounts) {
        this.userAccounts = userAccounts;
    }
    public Set getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Set subjects) {
        this.subjects = subjects;
    }




}


