package Entities;
// Generated May 13, 2017 5:10:37 PM by Hibernate Tools 4.3.1



/**
 * StudentExam generated by hbm2java
 */
public class StudentExam  implements java.io.Serializable {


     private int id;
     private Exam exam;
     private ExamsQuestion examsQuestion;
     private UserAccount userAccount;
     private Integer answerId;

    public StudentExam() {
    }

	
    public StudentExam(int id) {
        this.id = id;
    }
    public StudentExam(int id, Exam exam, ExamsQuestion examsQuestion, UserAccount userAccount, Integer answerId) {
       this.id = id;
       this.exam = exam;
       this.examsQuestion = examsQuestion;
       this.userAccount = userAccount;
       this.answerId = answerId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Exam getExam() {
        return this.exam;
    }
    
    public void setExam(Exam exam) {
        this.exam = exam;
    }
    public ExamsQuestion getExamsQuestion() {
        return this.examsQuestion;
    }
    
    public void setExamsQuestion(ExamsQuestion examsQuestion) {
        this.examsQuestion = examsQuestion;
    }
    public UserAccount getUserAccount() {
        return this.userAccount;
    }
    
    public void setUserAccount(UserAccount userAccount) {
        this.userAccount = userAccount;
    }
    public Integer getAnswerId() {
        return this.answerId;
    }
    
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }




}


