package Entities;
// Generated May 13, 2017 5:10:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private int id;
     private Course course;
     private Semester semester;
     private Specialitie specialitie;
     private String name;
     private Set questions = new HashSet(0);
     private Set exams = new HashSet(0);
     private Set userAccounts = new HashSet(0);

    public Subject() {
    }

	
    public Subject(int id) {
        this.id = id;
    }
    public Subject(int id, Course course, Semester semester, Specialitie specialitie, String name, Set questions, Set exams, Set userAccounts) {
       this.id = id;
       this.course = course;
       this.semester = semester;
       this.specialitie = specialitie;
       this.name = name;
       this.questions = questions;
       this.exams = exams;
       this.userAccounts = userAccounts;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Semester getSemester() {
        return this.semester;
    }
    
    public void setSemester(Semester semester) {
        this.semester = semester;
    }
    public Specialitie getSpecialitie() {
        return this.specialitie;
    }
    
    public void setSpecialitie(Specialitie specialitie) {
        this.specialitie = specialitie;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }
    public Set getExams() {
        return this.exams;
    }
    
    public void setExams(Set exams) {
        this.exams = exams;
    }
    public Set getUserAccounts() {
        return this.userAccounts;
    }
    
    public void setUserAccounts(Set userAccounts) {
        this.userAccounts = userAccounts;
    }




}


