package Entities;
// Generated May 13, 2017 5:10:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserAccount generated by hbm2java
 */
public class UserAccount  implements java.io.Serializable {


     private int id;
     private Role role;
     private Specialitie specialitie;
     private Subject subject;
     private String username;
     private String password;
     private String fisrtName;
     private String lastName;
     private Boolean gender;
     private String email;
     private String address;
     private String phone;
     private Date birthDay;
     private Set exams = new HashSet(0);
     private Set studentExams = new HashSet(0);

    public UserAccount() {
    }

	
    public UserAccount(int id, String username, String password, String email) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.email = email;
    }
    public UserAccount(int id, Role role, Specialitie specialitie, Subject subject, String username, String password, String fisrtName, String lastName, Boolean gender, String email, String address, String phone, Date birthDay, Set exams, Set studentExams) {
       this.id = id;
       this.role = role;
       this.specialitie = specialitie;
       this.subject = subject;
       this.username = username;
       this.password = password;
       this.fisrtName = fisrtName;
       this.lastName = lastName;
       this.gender = gender;
       this.email = email;
       this.address = address;
       this.phone = phone;
       this.birthDay = birthDay;
       this.exams = exams;
       this.studentExams = studentExams;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public Specialitie getSpecialitie() {
        return this.specialitie;
    }
    
    public void setSpecialitie(Specialitie specialitie) {
        this.specialitie = specialitie;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFisrtName() {
        return this.fisrtName;
    }
    
    public void setFisrtName(String fisrtName) {
        this.fisrtName = fisrtName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Date getBirthDay() {
        return this.birthDay;
    }
    
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }
    public Set getExams() {
        return this.exams;
    }
    
    public void setExams(Set exams) {
        this.exams = exams;
    }
    public Set getStudentExams() {
        return this.studentExams;
    }
    
    public void setStudentExams(Set studentExams) {
        this.studentExams = studentExams;
    }




}


